version: '3.8'

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    networks:
      - defaulf
    entrypoint: ["streamlit", "run", "Streamlit.py", "--server.port=8501", "--server.address=0.0.0.0"]
    restart: unless-stopped

  web:
    build: .
    ports:
      - "8500:8500"
    networks:
      - defaulf
    depends_on:
      - streamlit
    entrypoint: ["gunicorn", "-w", "1", "-b", ":8500", "main:app"]
    restart: unless-stopped

networks:
  defaulf:
    driver: bridge